import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f9faf5',
        surface: '#f9faf5',
        'surface-dim': '#d9dad6',
        'surface-bright': '#f9faf5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4ef',
        'surface-container': '#edeee9',
        'surface-container-high': '#e7e9e4',
        'surface-container-highest': '#e2e3de',
        'on-surface': '#1a1c19',
        'on-surface-variant': '#474834',
        'on-background': '#1a1c19',
        outline: '#777962',
        'outline-variant': '#c8c8ae',
        primary: '#5b6400',
        'on-primary': '#ffffff',
        'primary-container': '#d1e231',
        'on-primary-container': '#5a6300',
        secondary: '#5a5d70',
        'on-secondary': '#ffffff',
        'secondary-container': '#dee1f8',
        'on-secondary-container': '#606376',
        tertiary: '#ae2f34',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ffcbc8',
        'on-tertiary-container': '#ac2e34',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'margin-mobile': '20px',
        'gutter-mobile': '12px',
      },
    },
  },
  plugins: [],
};

export default config;
